In [1]:
import numpy as np

A = np.arange(1,13).reshape(3,4)
v = np.array([1,2,3,4])

Av = np.dot(A, v)
print(Av)

[ 30  70 110]


In [2]:
import numpy as np

A = np.arange(1,13).reshape(3,4)
B = np.arange(13,21).reshape(4,2)

AB = np.dot(A, B)
print(AB)

[[170 180]
 [426 452]
 [682 724]]


In [3]:
impor t numpy a s np
from s k l e a r n impor t d a t a s e t s

i r i s = d a t a s e t s . l o a d i r i s ( )

The d a t a s e t
d a t a s e t = i r i s [ ” data ” ]

# Mean
m = np . mean( d a t a s e t , a x i s=0 )

# C en t e r ed d a t a s e t
v e c t o r s = d a t a s e t - m

# C o v a r i a n c e
N = l e n ( v e c t o r s )
# B i a s ed
Q = np . dot ( v e c t o r s .T, v e c t o r s ) /N
Q = np . cov ( d a t a s e t , rowva r=F a l s e , ddof=0 ) # ddof = d e l t a d e g r e e s of freedom
Q = np . cov ( d a t a s e t .T, ddof=0 )

# Unbia s ed
Q = np . dot ( v e c t o r s .T, v e c t o r s ) / (N- 1 )
Q = np . cov ( d a t a s e t , rowva r=F a l s e )
Q = np . cov ( d a t a s e t .T)

# To t a l V a r i a n c e
TV = np . t r a c e (Q)

SyntaxError: invalid character '”' (U+201D) (3532136656.py, line 7)

In [5]:
import numpy as np  
from sklearn import datasets  

# Load the Iris dataset  
iris = datasets.load_iris()  
dataset = iris["data"]  

# Compute the mean  
mean = np.mean(dataset, axis=0)  

# Center the dataset  
centered_dataset = dataset - mean  

# Compute the covariance matrix (biased)  
N = len(centered_dataset)  
biased_cov = np.dot(centered_dataset.T, centered_dataset) / N  
biased_cov = np.cov(dataset, rowvar=False, ddof=0)  
biased_cov = np.cov(dataset.T, ddof=0)  

# Compute the covariance matrix (unbiased)  
unbiased_cov = np.dot(centered_dataset.T, centered_dataset) / (N - 1)  
unbiased_cov = np.cov(dataset, rowvar=False)  
unbiased_cov = np.cov(dataset.T)  

# Compute the total variance  
total_variance = np.trace(unbiased_cov)  

print("Mean:", mean)  
print("Biased covariance matrix:\n", biased_cov)  
print("Unbiased covariance matrix:\n", unbiased_cov)  
print("Total variance:\n", total_variance)


Mean: [5.84333333 3.05733333 3.758      1.19933333]
Biased covariance matrix:
 [[ 0.68112222 -0.04215111  1.26582     0.51282889]
 [-0.04215111  0.18871289 -0.32745867 -0.12082844]
 [ 1.26582    -0.32745867  3.09550267  1.286972  ]
 [ 0.51282889 -0.12082844  1.286972    0.57713289]]
Unbiased covariance matrix:
 [[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]
Total variance:
 4.572957046979867
