In [41]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("defined Matrix is :\n",A)
print("Dimention fo Matrix (Row * columon ):", A.shape)
print("the Numbers of Rows of Matrix:", len(A))
print("len function returns the Numbers of elemnts of Matrix in array ([[1,2,3],[4,5,6],[7,8,9]]):", len(A))
print("First Row :",A[0])
print("second Row :",A[1])
print("3rd Row :",A[2])
print("access to element(3,3) :",A[2,2]," \n Notice : Index strats from Zero in Python ")

defined Matrix is :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Dimention fo Matrix (Row * columon ): (4, 3)
the Numbers of Rows of Matrix: 4
len function returns the Numbers of elemnts of Matrix in array ([[1,2,3],[4,5,6],[7,8,9]]): 4
First Row : [1 2 3]
second Row : [4 5 6]
3rd Row : [7 8 9]
access to element(3,3) : 9  
 Notice : Index strats from Zero in Python 


In [47]:
print("slice of Matrix [1:3]:",A[1:3],"\n it means 1 and 2 , in other words Row number 2 and 3 in general")
print("slice of Matrix [:3]:",A[:3])
print("slice of Matrix [1:]:",A[1:])

slice of Matrix [1:3]: [[4 5 6]
 [7 8 9]] 
 it means 1 and 2 , in other words Row number 2 and 3 in general
slice of Matrix [:3]: [[1 2 3]
 [4 5 6]
 [7 8 9]]
slice of Matrix [1:]: [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [67]:
A_t=np.transpose(A)
print("Transpos of Matrix A is :\n",A_t)

print("first methode : Transpos of Matrix A is (np.transpose(A)) :\n",A.T,
      "\n second one : this methode is accessible when matrix A created by np.array '''(A.T)'''")

Transpos of Matrix A is :
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
first methode : Transpos of Matrix A is (np.transpose(A)) :
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] 
 second one : this methode is accessible when matrix A created by np.array '''(A.T)'''


In [71]:
v1=[1,6,3]
v2=[10,5,3]
v3=[1,4,7]
v4=[1,5,9]
B=np.array((v1,v2,v3,v4))
print("defined Matrix with Row Vecotrs  is :\n",B)

B=np.array((v1,v2,v3,v4))
print("defined Matrix with Col Vecotrs  is :\n",B.T)

defined Matrix with Row Vecotrs  is :
 [[ 1  6  3]
 [10  5  3]
 [ 1  4  7]
 [ 1  5  9]]
defined Matrix with Col Vecotrs  is :
 [[ 1 10  1  1]
 [ 6  5  4  5]
 [ 3  3  7  9]]


In [73]:
v1=[1,6,3]
v2=[10,5,3]
v3=[1,4,7]
v4=[1,5,9]
B=np.row_stack((v1,v2,v3,v4))
print("defined Matrix with Row Vecotrs  is :\n",B)
B=np.column_stack((v1,v2,v3,v4))
print("defined Matrix with Col Vecotrs  is :\n",B)

defined Matrix with Row Vecotrs  is :
 [[ 1  6  3]
 [10  5  3]
 [ 1  4  7]
 [ 1  5  9]]
defined Matrix with Col Vecotrs  is :
 [[ 1 10  1  1]
 [ 6  5  4  5]
 [ 3  3  7  9]]


In [91]:
import numpy as np
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()


# The dataset
dataset = iris["data"]
print("iris [head(10)] :\n",pd.DataFrame(data=dataset).head(10))
# To center the dataset
m = np.mean(dataset,axis=0)
vectors = dataset - m
print("means : \n ",m)
# To make a data frame
centered_df = pd.DataFrame(data=vectors)
print("\n centered iris [head(10)]:\n",centered_df.head(10))

iris [head(10)] :
      0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
5  5.4  3.9  1.7  0.4
6  4.6  3.4  1.4  0.3
7  5.0  3.4  1.5  0.2
8  4.4  2.9  1.4  0.2
9  4.9  3.1  1.5  0.1
means : 
  [5.84333333 3.05733333 3.758      1.19933333]

 centered iris [head(10)]:
           0         1      2         3
0 -0.743333  0.442667 -2.358 -0.999333
1 -0.943333 -0.057333 -2.358 -0.999333
2 -1.143333  0.142667 -2.458 -0.999333
3 -1.243333  0.042667 -2.258 -0.999333
4 -0.843333  0.542667 -2.358 -0.999333
5 -0.443333  0.842667 -2.058 -0.799333
6 -1.243333  0.342667 -2.358 -0.899333
7 -0.843333  0.342667 -2.258 -0.999333
8 -1.443333 -0.157333 -2.358 -0.999333
9 -0.943333  0.042667 -2.258 -1.099333


In [97]:
import numpy as np

A = np.zeros((4,3))
print("zero :\n", A)
B = np.eye(3)
print("squared Uniq :\n",B)
C = np.eye(4,3)
print("Unsquared Uniq :\n",C)
D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(" Matrix : \n",D)
E = np.diag([1,2,3,4])
print("diage Matrix : \n",E)


print("A+C :\n ",A+C)
print("C+D :\n " ,C+D)
print("4*D :\n ",4*D)
print("-D :\n ",-D)
print("-2*D :\n ",-2*D)

zero :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
squared Uniq :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Unsquared Uniq :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
 Matrix : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
diage Matrix : 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
A+C :
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
C+D :
  [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]
 [10. 11. 12.]]
4*D :
  [[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]
-D :
  [[ -1  -2  -3]
 [ -4  -5  -6]
 [ -7  -8  -9]
 [-10 -11 -12]]
-2*D :
  [[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]
 [-20 -22 -24]]


In [101]:
import numpy as np

u = np.array([1,2,3])
v = np.array([4, 5, 6])

u_dot_v = np.dot(u,v)
print(u_dot_v)

u_dot_v_ = u[0]*v[0] + u[1]*v[1] + u[2]*v[2]
print(u_dot_v_)

print(u_dot_v == u_dot_v_)# == is suitable for string and integers no for float type

print(" == is suitable for string and integers no for float type")

32
32
True
 == is suitable for string and integers no for float type
